/*
 * This Java source file was auto generated by running 'gradle buildInit'
 * by 'Felipe' at '02/04/17 11:22' with Gradle 2.14.1
 *
 * @author Felipe, @date 02/04/17 11:22
 */
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan({"togglz"})
public class Boot  {
	public static void main(String[] args) {
		SpringApplication.run(Boot.class, args);
	}
}
